flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 2%
      - type: patch
        target: 90%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: grai-server #fill in your own flag name
      paths:
        - grai-server #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: grai-frontend #fill in your own flag name
      paths:
        - grai-frontend #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%

ignore:
  - "**/tests/*"
  - "**/test_*.py"
  - "**/*.test.*"
