# Generated by Django 4.2.6 on 2023-10-20 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("chat_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("message_number", models.IntegerField(default=0)),
                (
                    "role",
                    models.CharField(choices=[("user", "user"), ("agent", "agent")], default="user", max_length=255),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="workspaces.membership",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["chat_id"], name="grAI_userch_chat_id_730147_idx"),
                    models.Index(fields=["membership", "created_at"], name="grAI_userch_members_65b04e_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userchat",
            constraint=models.UniqueConstraint(
                fields=("chat_id", "message_number"), name="Message numbers are unique for each chat"
            ),
        ),
    ]
