# Generated by Django 4.2.6 on 2023-10-23 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0007_workspace_ai_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                ("chat_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="workspaces.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("visible", models.BooleanField()),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("agent", "agent"), ("system", "system")],
                        default="user",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="grAI.userchat"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="userchat",
            index=models.Index(fields=["chat_id"], name="grAI_userch_chat_id_730147_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["created_at"], name="grAI_messag_created_7c8856_idx"),
        ),
    ]
