# Generated by Django 4.1.3 on 2022-12-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_edges",
                to="lineage.node",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_edges",
                to="lineage.node",
            ),
        ),
    ]
