# Generated by Django 4.1.4 on 2022-12-19 10:14

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        ("lineage", "0002_alter_edge_destination_alter_edge_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="workspace",
            field=models.ForeignKey(
                default="198e90f3-112e-4a11-84e7-1b5a4f02cec1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="workspace",
            field=models.ForeignKey(
                default="198e90f3-112e-4a11-84e7-1b5a4f02cec1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="edge",
            name="destination",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_edges",
                to="lineage.node",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_edges",
                to="lineage.node",
            ),
        ),
    ]
