# Generated by Django 4.1.3 on 2022-12-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        ("lineage", "0002_alter_edge_destination_alter_edge_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="edge",
            name="workspace",
            field=models.ForeignKey(
                default="198e90f3-112e-4a11-84e7-1b5a4f02cec1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="workspace",
            field=models.ForeignKey(
                default="198e90f3-112e-4a11-84e7-1b5a4f02cec1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
    ]
