# Generated by Django 4.1.4 on 2022-12-31 10:50

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0001_initial"),
        ("lineage", "0002_alter_edge_destination_alter_edge_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="edge",
            name="Edge namespaces/name uniqueness",
        ),
        migrations.RemoveConstraint(
            model_name="node",
            name="Node namespaces/name uniqueness",
        ),
        migrations.RemoveIndex(
            model_name="edge",
            name="lineage_edg_is_acti_1522cd_idx",
        ),
        migrations.RemoveIndex(
            model_name="edge",
            name="lineage_edg_namespa_f8f692_idx",
        ),
        migrations.RemoveIndex(
            model_name="node",
            name="lineage_nod_namespa_742536_idx",
        ),
        migrations.AddField(
            model_name="edge",
            name="workspace",
            field=models.ForeignKey(
                default="85a3c968-15c4-4906-83ff-931a672c087f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="node",
            name="workspace",
            field=models.ForeignKey(
                default="85a3c968-15c4-4906-83ff-931a672c087f",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="edge",
            name="destination",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_edges",
                to="lineage.node",
            ),
        ),
        migrations.AlterField(
            model_name="edge",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_edges",
                to="lineage.node",
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["workspace", "is_active"], name="lineage_edg_workspa_b34f20_idx"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                fields=["workspace", "namespace", "name"],
                name="lineage_edg_workspa_24f7f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["workspace", "namespace", "name"],
                name="lineage_nod_workspa_065f65_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("workspace", "namespace", "name"),
                name="Edge namespaces/name uniqueness",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                fields=("workspace", "namespace", "name"),
                name="Node namespaces/name uniqueness",
            ),
        ),
    ]
