# Generated by Django 4.1.7 on 2023-04-03 15:01

from django.db import migrations
import django_multitenant.models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0003_name_uniqueness_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="edge",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="node",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
