# Generated by Django 4.2.1 on 2023-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0005_filter"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(fields=["workspace", "source", "destination"], name="lineage_edg_workspa_8dbd89_idx"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(models.F("workspace"), models.F("metadata__grai__edge_type"), name="lineage_edge_type"),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                models.F("metadata__grai__edge_type"), models.F("source"), name="lineage_edge_type_source"
            ),
        ),
        migrations.AddIndex(
            model_name="edge",
            index=models.Index(
                models.F("metadata__grai__edge_type"), models.F("destination"), name="lineage_edge_type_destination"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(models.F("workspace"), models.F("metadata__grai__node_type"), name="lineage_node_type"),
        ),
    ]
