# Generated by Django 4.2 on 2023-05-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0020_alter_run_action"),
        ("lineage", "0006_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="connections.connection",
            ),
        ),
    ]
