# Generated by Django 4.2.1 on 2023-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0007_event_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default="2023-05-10T12:33:33.819138+00:00"),
            preserve_default=False,
        ),
    ]
