# Generated by Django 4.2.1 on 2023-05-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0008_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reference",
            field=models.CharField(default="1", max_length=255),
            preserve_default=False,
        ),
    ]
