# Generated by Django 4.2.2 on 2023-06-16 16:39

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import lineage.managers
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx"),
        ("lineage", "0008_alter_edge_managers_alter_node_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edges",
                    models.ManyToManyField(
                        related_name="data_sources", to="lineage.edge"
                    ),
                ),
                (
                    "nodes",
                    models.ManyToManyField(
                        related_name="data_sources", to="lineage.node"
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "name"],
                        name="lineage_sou_workspa_e22922_idx",
                    )
                ],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", lineage.managers.SourceManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                fields=("workspace", "name"), name="Source name uniqueness"
            ),
        ),
    ]
