# Generated by Django 4.2.1 on 2023-05-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0009_source_source_source_name_uniqueness"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="edges",
            field=models.ManyToManyField(related_name="data_sources", to="lineage.edge"),
        ),
    ]
