# Generated by Django 4.2.1 on 2023-05-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0010_source_edges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="data_source",
        ),
        migrations.RemoveField(
            model_name="node",
            name="data_source",
        ),
    ]
