# Generated by Django 4.2.3 on 2023-07-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lineage", "0011_remove_edge_data_source_remove_node_data_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edge",
            name="display_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="edge",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="edge",
            name="namespace",
            field=models.TextField(default="default"),
        ),
        migrations.AlterField(
            model_name="node",
            name="display_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="node",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="node",
            name="namespace",
            field=models.TextField(default="default"),
        ),
    ]
