# Generated by Django 4.2.4 on 2023-08-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0013_auto_20230727_2034"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
