# Generated by Django 4.2.4 on 2023-08-15 12:17

from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0014_source_priority"),
    ]

    operations = [
        migrations.RunSQL(
            """
    ALTER TABLE IF EXISTS public.lineage_source_nodes
    DROP CONSTRAINT IF EXISTS lineage_source_nodes_node_id_3d3dc41a_fk_lineage_node_id,
    ADD CONSTRAINT lineage_source_nodes_node_id_3d3dc41a_fk_lineage_node_id
    FOREIGN KEY (node_id)
    REFERENCES public.lineage_node (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED
                          """
        ),
        migrations.RunSQL(
            """
    ALTER TABLE IF EXISTS public.lineage_source_edges
    DROP CONSTRAINT IF EXISTS lineage_source_edges_edge_id_6dc361da_fk_lineage_edge_id,
    ADD CONSTRAINT lineage_source_edges_edge_id_6dc361da_fk_lineage_edge_id
    FOREIGN KEY (edge_id)
    REFERENCES public.lineage_edge (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;
                          """
        ),
    ]
