# Generated by Django 4.2.5 on 2023-09-12 15:32

from django.db import migrations
from lineage.models import Source


def forwards(apps, schema_editor):
    for source in Source.objects.iterator(chunk_size=1000):
        source.nodes.remove(*source.nodes.filter(workspace__id__ne=source.workspace))
        source.edges.remove(*source.edges.filter(workspace__id__ne=source.workspace))


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0016_alter_edge_metadata_alter_node_metadata"),
    ]

    operations = [migrations.RunPython(forwards)]
