# Generated by Django 4.2.5 on 2023-09-12 15:32

from django.db import migrations
from lineage.models import Source
from django.db.models import Q


def forwards(apps, schema_editor):
    for source in Source.objects.iterator(chunk_size=1000):
        query = Q(workspace__id=source.workspace)
        source.nodes.remove(*source.nodes.filter(~query))
        source.edges.remove(*source.edges.filter(~query))


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0016_alter_edge_metadata_alter_node_metadata"),
    ]

    operations = [migrations.RunPython(forwards)]
