# Generated by Django 4.1.3 on 2022-12-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("namespaces", "0002_namespace_workspace"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ServiceAPIKey",
        ),
    ]
