# Generated by Django 4.2.5 on 2023-09-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
