# Generated by Django 4.1.7 on 2023-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_organisation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("member", "member"), ("read_only", "read_only")],
                default="member",
                max_length=255,
            ),
        ),
    ]
