# Generated by Django 4.1.7 on 2023-04-03 15:01

from django.db import migrations, models
import django_multitenant.models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_alter_membership_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="membership",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="workspace",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="search_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
