# Generated by Django 4.2.1 on 2023-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_alter_membership_managers_alter_workspace_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
