# Generated by Django 4.2.1 on 2023-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0005_membership_hidden"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workspace",
            index=models.Index(fields=["name"], name="workspaces__name_5adeb1_idx"),
        ),
    ]
