# Generated by Django 4.2.6 on 2023-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
