# Generated by Django 4.2.7 on 2023-12-01 17:14

from django.db import migrations, models
from workspaces.models import Workspace


def disable_default_ai_enabled(apps, schema_editor):
    # Require users to explicitly enable AI components
    Workspace.objects.update(ai_enabled=False)


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0008_workspace_sample_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="ai_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(disable_default_ai_enabled, migrations.RunPython.noop),
    ]
