version: "3.7"

services:
  postgres:
    image: ankane/pgvector
    volumes:
     - ./dev-database/schemas:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: grai
      POSTGRES_PASSWORD: grai
      POSTGRES_DB: grai
    ports:
      - 5433:5432
