version: "3.7"

services:
  db:
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=grai
      - POSTGRES_PASSWORD=grai
      - POSTGRES_DB=grai
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U grai"
      interval: 2s
      timeout: 2s
      retries: 15

  the_guide:
    image: ghcr.io/grai-io/grai-core/grai-server:latest
    # extra_hosts are not required but provided so users can easily connect to services running on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=default
      - SERVER_HOST=localhost
      - FRONTEND_HOST=localhost
      - FRONTEND_URL=http://localhost:3000
      - REDIS_HOST=redis
    depends_on:
      - db
    healthcheck:
      test: "curl -f -v -H 'Accept: application/json' http://localhost:8000/health/"
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 20s

  celery_worker:
    image: ghcr.io/grai-io/grai-core/grai-worker:latest
    # extra_hosts are not required but provided so users can easily connect to services running on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_volume:/usr/src/app/media
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=default
      - SERVER_HOST=localhost
      - FRONTEND_HOST=localhost
      - FRONTEND_URL=http://localhost:3000
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db

  celery_beat_worker:
    image: ghcr.io/grai-io/grai-core/grai-beat-worker:latest
    # extra_hosts are not required but provided so users can easily connect to services running on the host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_volume:/usr/src/app/media
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=grai
      - DB_USER=grai
      - DB_PASSWORD=grai
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
      - DJANGO_SUPERUSER_WORKSPACE=default
      - SERVER_HOST=localhost
      - FRONTEND_HOST=localhost
      - FRONTEND_URL=http://localhost:3000
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db

  frontend:
    image: ghcr.io/grai-io/grai-core/grai-frontend:latest
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - the_guide

  redis:
    image: redis/redis-stack:6.2.6-v9
    restart: always
    ports:
      - 6379:6379
      - 8001:8001

volumes:
  media_volume:
