# Generated by Django 4.0.6 on 2022-08-02 02:40

import uuid

from django.conf import settings
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("namespace", models.CharField(default="default", max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Connector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="connector",
            index=models.Index(
                fields=["is_active"], name="connections_is_acti_b59726_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="connector",
            index=models.Index(fields=["name"], name="connections_name_017e0f_idx"),
        ),
        migrations.AddConstraint(
            model_name="connector",
            constraint=models.UniqueConstraint(
                fields=("name",), name="Name uniqueness"
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="connector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="connections.connector",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["namespace", "name"], name="connections_namespa_a34c70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="connection",
            constraint=models.UniqueConstraint(
                fields=("namespace", "name"),
                name="Node namespaces/name uniqueness - Connection",
            ),
        ),
    ]
