# Generated by Django 4.1.4 on 2022-12-19 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="workspace",
            field=models.ForeignKey(
                default="198e90f3-112e-4a11-84e7-1b5a4f02cec1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections",
                to="workspaces.workspace",
            ),
            preserve_default=False,
        ),
    ]
