# Generated by Django 4.1.3 on 2022-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0002_alter_connection_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="secrets",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
