# Generated by Django 4.1.5 on 2023-01-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("connections", "0002_alter_connection_created_by_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="schedules",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
