# Generated by Django 4.1.5 on 2023-01-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0003_connection_schedules_connection_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="connector",
            name="coming_soon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connector",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
