# Generated by Django 4.1.5 on 2023-01-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0004_connector_category_connector_coming_soon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.CharField(
                choices=[("PostgreSQL", "PostgreSQL"), ("Snowflake", "Snowflake")],
                max_length=255,
            ),
        ),
    ]
