# Generated by Django 4.1.5 on 2023-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0005_alter_connector_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.CharField(
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("Snowflake", "Snowflake"),
                    ("dbt", "dbt"),
                    ("YAML File", "YAML File"),
                ],
                max_length=255,
            ),
        ),
    ]
