# Generated by Django 4.1.6 on 2023-02-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0007_run_connector_alter_run_connection_runfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.CharField(
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("Snowflake", "Snowflake"),
                    ("dbt", "dbt"),
                    ("YAML File", "YAML File"),
                    ("Microsoft SQL Server", "Microsoft SQL Server"),
                ],
                max_length=255,
            ),
        ),
    ]
