# Generated by Django 4.1.6 on 2023-02-07 15:26

from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Run = apps.get_model("connections", "Run")
    db_alias = schema_editor.connection.alias
    runs = Run.objects.using(db_alias).filter(connection_id=None).all()

    for run in runs:
        run.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0008_alter_connector_name"),
    ]

    operations = [
        # migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name="run",
            name="connector",
        ),
        migrations.AlterField(
            model_name="run",
            name="connection",
            field=django_multitenant.fields.TenantForeignKey(
                default="1ad8e35f-5a4c-4062-a209-a9d47a817c8d",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="connections.connection",
            ),
            preserve_default=False,
        ),
    ]
