# Generated by Django 4.1.6 on 2023-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0009_remove_run_connector_alter_run_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="temp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="run",
            name="trigger",
            field=models.JSONField(default=dict),
        ),
    ]
