# Generated by Django 4.1.7 on 2023-02-15 12:39

import uuid

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Run = apps.get_model("connections", "Run")
    Connection = apps.get_model("connections", "Connection")
    db_alias = schema_editor.connection.alias
    runs = Run.objects.using(db_alias).filter(connection_id=None).all()

    for run in runs:
        connection_name = f"{run.connector.name} {uuid.uuid4()}"

        connection = Connection.objects.using(db_alias).create(
            workspace=run.workspace,
            connector=run.connector,
            name=connection_name,
            namespace=run.namespace,
            is_active=True,
            temp=True,
        )
        run.connection = connection
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0010_alter_connector_name"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name="run",
            name="connector",
        ),
        migrations.AddField(
            model_name="connection",
            name="temp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "postgres"),
                    ("snowflake", "snowflake"),
                    ("dbt", "dbt"),
                    ("yaml_file", "yaml_file"),
                    ("mssql", "mssql"),
                    ("bigquery", "bigquery"),
                    ("fivetran", "fivetran"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="action",
            field=models.CharField(
                choices=[("tests", "tests"), ("update", "update")], default="update", max_length=255
            ),
        ),
    ]
