# Generated by Django 4.1.6 on 2023-02-08 16:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0010_remove_run_connector_connection_temp_run_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("github", "github")], max_length=255)),
                ("owner", models.CharField(editable=False, max_length=255)),
                ("repo", models.CharField(editable=False, max_length=255)),
                ("installation_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
