# Generated by Django 4.1.6 on 2023-02-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0011_repository"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type"], name="connections_type_61f905_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner"], name="connections_type_6e3a7e_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner", "repo"], name="connections_type_0f2c4c_idx"),
        ),
    ]
