# Generated by Django 4.1.7 on 2023-02-15 12:39

import django.db.models.deletion
import django_multitenant.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0011_remove_run_connector_connection_temp_connector_slug_and_more"),
        ("installations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="installations.commit",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="trigger",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="run",
            name="connection",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="connections.connection"
            ),
        ),
    ]
