# Generated by Django 4.1.6 on 2023-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0012_repository_connections_type_61f905_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"verbose_name_plural": "repositories"},
        ),
        migrations.AddField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PostgreSQL", "PostgreSQL"),
                    ("Snowflake", "Snowflake"),
                    ("dbt", "dbt"),
                    ("YAML File", "YAML File"),
                    ("Microsoft SQL Server", "Microsoft SQL Server"),
                    ("Google BigQuery", "Google BigQuery"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
