# Generated by Django 4.1.6 on 2023-02-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0013_alter_repository_options_connector_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "postgres"),
                    ("snowflake", "snowflake"),
                    ("dbt", "dbt"),
                    ("yaml_file", "yaml_file"),
                    ("mssql", "mssql"),
                    ("bigquery", "bigquery"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="trigger",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
