# Generated by Django 4.1.6 on 2023-02-10 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0014_alter_connector_slug_alter_run_trigger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Repository",
        ),
    ]
