# Generated by Django 4.1.7 on 2023-02-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0014_alter_connection_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="action",
            field=models.CharField(
                choices=[("tests", "tests"), ("update", "update"), ("validate", "validate")],
                default="update",
                max_length=255,
            ),
        ),
    ]
