# Generated by Django 4.1.6 on 2023-02-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("installations", "0002_branch_pullrequest_commit_and_more"),
        ("connections", "0015_delete_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="commit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="runs",
                to="installations.commit",
            ),
        ),
    ]
