# Generated by Django 4.1.7 on 2023-04-03 15:01

from django.db import migrations
import django_multitenant.models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0015_alter_run_action"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="connection",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="run",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
