# Generated by Django 4.1.7 on 2023-02-15 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0010_alter_connector_name"),
        ("connections", "0016_run_commit"),
    ]

    operations = []
