# Generated by Django 4.2 on 2023-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0017_alter_connector_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="connection",
            name="Node namespaces/name uniqueness - Connection",
        ),
        migrations.RemoveIndex(
            model_name="connection",
            name="connections_workspa_cf2dc2_idx",
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(fields=["workspace", "name"], name="connections_workspa_f19863_idx"),
        ),
    ]
