# Generated by Django 4.2 on 2023-05-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0019_alter_connector_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="action",
            field=models.CharField(
                choices=[("tests", "tests"), ("update", "update"), ("validate", "validate"), ("events", "events")],
                default="update",
                max_length=255,
            ),
        ),
    ]
