# Generated by Django 4.2.1 on 2023-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0019_alter_connector_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="events",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="run",
            name="action",
            field=models.CharField(
                choices=[
                    ("tests", "tests"),
                    ("update", "update"),
                    ("validate", "validate"),
                    ("events", "events"),
                    ("events_all", "events_all"),
                ],
                default="update",
                max_length=255,
            ),
        ),
    ]
