# Generated by Django 4.2.1 on 2023-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0020_alter_run_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="events",
            field=models.BooleanField(default=False),
        ),
    ]
