# Generated by Django 4.2.1 on 2023-05-30 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0021_credential_remove_connection_metadata_and_more"),
        ("lineage", "0008_alter_edge_managers_alter_node_managers_source_and_more"),
        ("workspaces", "0006_workspace_workspaces__name_5adeb1_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="lineage.source",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="lineage.source",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connection",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="connections.credential",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="connections.credential",
            ),
        ),
    ]
