# Generated by Django 4.2.1 on 2023-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0021_connector_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="action",
            field=models.CharField(
                choices=[
                    ("tests", "tests"),
                    ("update", "update"),
                    ("validate", "validate"),
                    ("events", "events"),
                    ("events_all", "events_all"),
                ],
                default="update",
                max_length=255,
            ),
        ),
    ]
