# Generated by Django 4.2.3 on 2023-07-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0021_alter_run_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "postgres"),
                    ("snowflake", "snowflake"),
                    ("dbt", "dbt"),
                    ("dbt_cloud", "dbt_cloud"),
                    ("yaml_file", "yaml_file"),
                    ("mssql", "mssql"),
                    ("bigquery", "bigquery"),
                    ("fivetran", "fivetran"),
                    ("mysql", "mysql"),
                    ("redshift", "redshift"),
                    ("metabase", "metabase"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
