# Generated by Django 4.2.1 on 2023-05-30 14:34

import django.db.models.deletion
from django.db import migrations
from lineage.models import Source
from connections.models import Credential
from django.db import migrations, models


def create_sources(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Connection = apps.get_model("connections", "Connection")
    # Run = apps.get_model("connections", "Run")

    for connection in Connection.objects.all():
        source = Source()
        source.workspace_id = connection.workspace_id
        source.name = connection.name
        source.save()

        connection.source_id = source.id
        connection.save()

        # runs = Run.objects.filter(connection=connection)

        # for run in runs:
        #     run.source = source
        #     run.save()


def create_credentials(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # Credential = apps.get_model("connections", "Credential")
    Connection = apps.get_model("connections", "Connection")
    for connection in Connection.objects.all():
        credential = Credential()
        credential.workspace_id = connection.workspace_id
        credential.name = connection.name
        credential.metadata = connection.metadata
        credential.secrets = connection.secrets
        credential.save()

        connection.credential_id = credential.id
        connection.save()

        # for run in connection.runs.all():
        #     run.credential = credential
        #     run.save()


def add_credential_to_run(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Run = apps.get_model("connections", "Run")

    for run in Run.objects.all():
        run.credential_id = run.connection.credential_id
        run.save()


def add_source_to_run(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Run = apps.get_model("connections", "Run")

    for run in Run.objects.all():
        run.source = run.connection.source
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0022_connection_source_run_source_credential_workspace_and_more"),
    ]

    operations = [
        migrations.RunPython(create_sources),
        migrations.RunPython(create_credentials),
        migrations.RunPython(add_credential_to_run),
        migrations.RunPython(add_source_to_run),
    ]
