# Generated by Django 4.2.2 on 2023-06-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0011_remove_edge_data_source_remove_node_data_source"),
        ("connections", "0023_connection_source_run_source_alter_run_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="lineage.source",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="run",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="lineage.source",
            ),
            preserve_default=False,
        ),
    ]
