# Generated by Django 4.2.1 on 2023-05-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lineage", "0008_alter_edge_managers_alter_node_managers_source_and_more"),
        ("connections", "0023_alter_run_credential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="secrets",
        ),
        migrations.RemoveField(
            model_name="run",
            name="connection",
        ),
        migrations.AlterField(
            model_name="connection",
            name="credential",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="connections", to="connections.credential"
            ),
        ),
        migrations.AlterField(
            model_name="connection",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="connections", to="lineage.source"
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="lineage.source"
            ),
        ),
    ]
