# Generated by Django 4.2.1 on 2023-05-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0024_alter_connection_credential_alter_connection_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
