# Generated by Django 4.2.1 on 2023-05-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0025_credential_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="credential",
        ),
        migrations.RemoveField(
            model_name="run",
            name="credential",
        ),
        migrations.AddField(
            model_name="connection",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="connection",
            name="secrets",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="connections.connection",
            ),
        ),
        migrations.DeleteModel(
            name="Credential",
        ),
    ]
