# Generated by Django 4.2.5 on 2023-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0025_alter_connector_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="input",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "postgres"),
                    ("snowflake", "snowflake"),
                    ("dbt", "dbt"),
                    ("dbt_cloud", "dbt_cloud"),
                    ("yaml_file", "yaml_file"),
                    ("mssql", "mssql"),
                    ("bigquery", "bigquery"),
                    ("fivetran", "fivetran"),
                    ("mysql", "mysql"),
                    ("redshift", "redshift"),
                    ("metabase", "metabase"),
                    ("looker", "looker"),
                    ("openlineage", "openlineage"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
