# Generated by Django 4.2.6 on 2023-10-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0026_run_input_alter_connector_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connector",
            name="coming_soon",
        ),
        migrations.AddField(
            model_name="connector",
            name="status",
            field=models.CharField(
                choices=[
                    ("coming_soon", "coming_soon"),
                    ("alpha", "alpha"),
                    ("beta", "beta"),
                    ("general_release", "general_release"),
                ],
                default="general_release",
                max_length=255,
            ),
        ),
    ]
