# Generated by Django 4.2.6 on 2023-10-30 16:54

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Connection = apps.get_model("connections", "Connection")

    Connection.objects.filter(temp=False).update(validated=True)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0027_remove_connector_coming_soon_connector_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
