# Generated by Django 4.2.7 on 2023-11-29 18:31

from django.db import migrations, models
import django.utils.timezone
from connections.models import DEFAULT_STATUS_PRIORITY


def populate_priority(apps, schema_editor):
    connector = apps.get_model("connections", "Connector")

    instances = connector.objects.all()
    for instance in instances:
        instance.priority = DEFAULT_STATUS_PRIORITY.get(instance.status, 100)

    connector.objects.bulk_update(instances, ["priority"])


class Migration(migrations.Migration):
    dependencies = [
        ("connections", "0029_alter_connection_source_alter_run_connection_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connector",
            options={"ordering": ["-priority", "name"]},
        ),
        migrations.AddField(
            model_name="connector",
            name="priority",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "Postgres"),
                    ("snowflake", "Snowflake"),
                    ("dbt", "dbt"),
                    ("dbt_cloud", "dbt Cloud"),
                    ("yaml_file", "YAML"),
                    ("mssql", "Microsoft SQL Server"),
                    ("bigquery", "Google BigQuery"),
                    ("fivetran", "Fivetran"),
                    ("mysql", "MySQL"),
                    ("redshift", "Amazon Redshift"),
                    ("metabase", "Metabase"),
                    ("looker", "Looker"),
                    ("openlineage", "OpenLineage"),
                    ("flatfile", "Flat File"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="status",
            field=models.CharField(
                choices=[
                    ("coming_soon", "Coming Soon"),
                    ("alpha", "Alpha"),
                    ("beta", "beta"),
                    ("general_release", "General Release"),
                ],
                default="general_release",
                max_length=255,
            ),
        ),
        migrations.RunPython(populate_priority, migrations.RunPython.noop),
    ]
