# Generated by Django 4.2.11 on 2024-05-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0030_alter_connector_options_connector_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="slug",
            field=models.CharField(
                blank=True,
                choices=[
                    ("postgres", "Postgres"),
                    ("snowflake", "Snowflake"),
                    ("dbt", "dbt"),
                    ("dbt_cloud", "dbt Cloud"),
                    ("yaml_file", "YAML"),
                    ("mssql", "Microsoft SQL Server"),
                    ("bigquery", "Google BigQuery"),
                    ("fivetran", "Fivetran"),
                    ("mysql", "MySQL"),
                    ("redshift", "Amazon Redshift"),
                    ("metabase", "Metabase"),
                    ("looker", "Looker"),
                    ("openlineage", "OpenLineage"),
                    ("flatfile", "Flat File"),
                    ("cube", "Cube"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("error", "Error")],
                default="pending",
                max_length=255,
            ),
        ),
    ]
