# Generated by Django 4.1.7 on 2023-03-22 17:59

import uuid

import django.db.models.deletion
import django_multitenant.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0003_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "channel",
                    models.CharField(
                        choices=[("slack", "slack"), ("email", "email"), ("pager_duty", "pager_duty")], max_length=255
                    ),
                ),
                ("channel_metadata", models.JSONField(default=dict)),
                ("triggers", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="alerts", to="workspaces.workspace"
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(fields=["workspace"], name="notificatio_workspa_b78bc8_idx"),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(fields=("workspace", "name"), name="Alert unique name per workspace"),
        ),
    ]
