# Generated by Django 4.1.6 on 2023-02-10 11:20

import uuid

import django.db.models.deletion
import django_multitenant.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0002_organisation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("github", "github")], max_length=255)),
                ("owner", models.CharField(editable=False, max_length=255)),
                ("repo", models.CharField(editable=False, max_length=255)),
                ("installation_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repositories",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type"], name="installatio_type_728bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner"], name="installatio_type_311c0e_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner", "repo"], name="installatio_type_5f2231_idx"),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("type", "owner", "repo"), name="Repository type/owner/repo uniqueness"
            ),
        ),
    ]
