# Generated by Django 4.1.7 on 2023-02-15 12:39

import uuid

import django.db.models.deletion
import django_multitenant.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0002_organisation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "branches",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("github", "github")], max_length=255)),
                ("owner", models.CharField(editable=False, max_length=255)),
                ("repo", models.CharField(editable=False, max_length=255)),
                ("installation_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "repositories",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="installations.branch",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="installations.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commits", to="installations.branch"
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="installations.pullrequest",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="installations.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commits", to="workspaces.workspace"
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="branch",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="installations.repository"
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="workspaces.workspace"
            ),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type"], name="installatio_type_728bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner"], name="installatio_type_311c0e_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["type", "owner", "repo"], name="installatio_type_5f2231_idx"),
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("workspace", "type", "owner", "repo"), name="Repository type/owner/repo uniqueness"
            ),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["reference"], name="installatio_referen_4b4fe8_idx"),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_395738_idx"),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Pull Request repository/reference uniqueness"
            ),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(fields=["reference"], name="installatio_referen_115842_idx"),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_abe94f_idx"),
        ),
        migrations.AddConstraint(
            model_name="commit",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Commit repository/reference uniqueness"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["reference"], name="installatio_referen_b776ed_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_68c7a0_idx"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Branch repository/reference uniqueness"
            ),
        ),
    ]
