# Generated by Django 4.1.6 on 2023-02-10 11:48

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_organisation_and_more"),
        ("installations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="installations.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="branches", to="workspaces.workspace"
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="installations.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pull_requests",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reference", models.CharField(editable=False, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commits", to="installations.branch"
                    ),
                ),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="installations.pullrequest",
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="installations.repository",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="commits", to="workspaces.workspace"
                    ),
                ),
            ],
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["reference"], name="installatio_referen_4b4fe8_idx"),
        ),
        migrations.AddIndex(
            model_name="pullrequest",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_395738_idx"),
        ),
        migrations.AddConstraint(
            model_name="pullrequest",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Pull Request repository/reference uniqueness"
            ),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(fields=["reference"], name="installatio_referen_115842_idx"),
        ),
        migrations.AddIndex(
            model_name="commit",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_abe94f_idx"),
        ),
        migrations.AddConstraint(
            model_name="commit",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Commit repository/reference uniqueness"
            ),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["reference"], name="installatio_referen_b776ed_idx"),
        ),
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(fields=["repository", "reference"], name="installatio_reposit_68c7a0_idx"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("repository", "reference"), name="Branch repository/reference uniqueness"
            ),
        ),
    ]
