# Generated by Django 4.1.6 on 2023-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("installations", "0002_branch_pullrequest_commit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "branches"},
        ),
        migrations.RemoveConstraint(
            model_name="repository",
            name="Repository type/owner/repo uniqueness",
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("workspace", "type", "owner", "repo"), name="Repository type/owner/repo uniqueness"
            ),
        ),
    ]
