# Generated by Django 4.1.6 on 2023-02-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("installations", "0004_pullrequest_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
