# Generated by Django 4.1.6 on 2023-02-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("installations", "0005_pullrequest_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
