version: "3.7"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
     - ./data/schema/:/scripts/
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: grai
      MSSQL_SA_PASSWORD: GraiGraiGr4i
      MSSQL_USER: grai
      MSSQL_PASSWORD: grai
    ports:
      - 1433:1433
    command:
    - /bin/bash
    - -c
    - |
      /opt/mssql/bin/sqlservr &
      sleep 30
      for foo in /scripts/*.sql
         do /opt/mssql-tools/bin/sqlcmd -U sa -P $$MSSQL_SA_PASSWORD -l 30 -e -i $$foo
      done
      sleep infinity
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q "SELECT 1" || exit 1
      interval: 3s
      timeout: 3s
      retries: 10
