services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    # image: mcr.microsoft.com/azure-sql-edge:latest
    volumes:
     - ./data/:/init
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: GraiGraiGr4i
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    command: ['/bin/bash', '-c', '/init/init-db.sh & /opt/mssql/bin/sqlservr']
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q 'select 1' -o /dev/null -b -No
      interval: 3s
      timeout: 3s
      retries: 10
