name: DBT Integration CI

on:
  pull_request:
    paths:
      - "grai-integrations/source-dbt/**"
      - "grai-client/**"
      - "grai-server/**"
      - ".github/workflows/integration-dbt-ci.yml"


concurrency:
  group: ${{ github.ref }}-integration-dbt-ci
  cancel-in-progress: true

env:
  project_dir: "grai-integrations/source-dbt"

jobs:
  lint-integration-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ vars.PY_VER }}"

      - run: pip install black isort

      - run: |
          black . --check
          isort . --profile black --check

  tests-integration-dbt:
    needs: lint-integration-dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ vars.PY_VER }}"

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "${{ vars.POETRY_VER }}"

      - run: poetry install

      - name: Run DBT Tests
        run: poetry run pytest
