name: Metabase Integration CI

on:
  pull_request:
    paths:
      - "grai-integrations/source-metabase/**"
      - "grai-client/**"
      - "grai-server/**"
      - ".github/workflows/integration-metabase-ci.yml"

concurrency:
  group: ${{ github.ref }}-metabase-ci
  cancel-in-progress: true


env:
  project_dir: "grai-integrations/source-metabase"

jobs:
  lint-integration-metabase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ vars.PY_VER }}"

      - run: pip install black isort

      - run: |
          black . --check
          isort . --profile black --check

  tests-integration-metabase:
    needs: lint-integration-metabase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ vars.PY_VER }}"

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "${{ vars.POETRY_VER }}"

      - run: poetry install

      - name: Start Metabase
        run: docker compose up -d

      - name: Wait for Metabase to start
        run: sleep 90

      - name: Run Metabase integration tests
        run: poetry run pytest
