name: DBT Integration CI

on:
  pull_request:
    paths:
      - "grai-integrations/source-dbt/**"
      - "grai-client/**"
      - "grai-server/**"


concurrency:
  group: ${{ github.ref }}-integration-dbt-ci
  cancel-in-progress: true

env:
  py_ver: "3.10"
  poetry_ver: "1.3.1"
  project_dir: "grai-integrations/source-dbt"

jobs:
  lint-integration-dbt:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.py_ver }}"

      - run: pip install black isort

      - run: |
          black . --check
          isort . --profile black --check

  tests-integration-dbt:
    needs: lint-integration-dbt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.py_ver }}"

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "${{ env.poetry_ver }}"

      - run: poetry install
      - run: poetry run pytest
