name: MySQL Integration CI

on:
  pull_request:
    paths:
      - "grai-integrations/source-metabase/**"
      - "grai-server/**"


concurrency:
  group: ${{ github.ref }}-metabase-ci
  cancel-in-progress: true


env:
  py_ver: "3.10"
  poetry_ver: "1.2.2"
  project_dir: "grai-integrations/source-metabase"
  DB_DATABASE: grai
  DB_USER: grai
  DB_PASSWORD: grai
  DB_HOST: localhost

jobs:
  lint-integration-metabase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ env.py_ver }}"

      - run: pip install black isort

      - run: |
          black . --check
          isort . --profile black --check

  tests-integration-metabase:
    needs: lint-integration-metabase
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.project_dir }}
    services:
      # Needs to somehow mount the metabase.db file....
      test_metabase:
        image: metabase/metabase:latest
        env:
          MB_DB_FILE: /metabase.db
        ports:
          - 3001:3000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Metabase
        working-directory: ${{ env.project_dir }}/init
        run: |
          sh init_metabase.sh

      - uses: actions/setup-python@v4
        with:
          python-version: "${{ env.py_ver }}"

      - run: |
          pip install pytest
          pip install .

      - run: pytest
