name: Review App Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Helm uninstall"
        continue-on-error: true
        uses: bitovi/github-actions-deploy-eks-helm@v1.0.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          namespace: pr-${{ github.event.number }}
          name: pr-${{ github.event.number }}
          action: uninstall
